"""Add updatedAt column to user table

Revision ID: 036b69aac8cb
Revises: 
Create Date: 2023-06-05 14:21:01.018740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036b69aac8cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###
